
[game]
# If the deck is shuffled every new game
shuffle = true
# Ids of the cards that will be included in a new deck
deck_ids = [8, 7, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1]
# Cards that the server will use
cards = [
    { id = 1, name = "Guard Odette" },
    { id = 2, name = "Priest Tomas" },
    { id = 3, name = "Baron Talus" },
    { id = 4, name = "Handmaid Susannah" },
    { id = 5, name = "Prince Arnaud" },
    { id = 6, name = "King Arnaud IV" },
    { id = 7, name = "Countess Wilhelmina" },
    { id = 8, name = "Princess Annette" },
]